name: Unseen
version: 1.1
main: me.Unseen.Unseen
api-version: 1.20
author: [nobstergo]
contributors: [alprny]
commands:
  unseen:
    description: Unseen plugin main command
    usage: /unseen <subcommand>
    permission: unseen.use
permissions:
  unseen.use:
    description: Allows use of /unseen info
    default: true
  unseen.admin:
    description: Admin permissions for reload & config editing
    default: op